### ISSUE TITLE
Packaging for Guix

### ISSUE THREAD

**Issue by Hellseher** [bufferswap/ViralityEngine#28]
Hi,

Would you be interested to have your project packed in Guix package registry?
I've already packed the whole chain of missing system required for Virality
(e.g. [cl-sdl2](https://packages.guix.gnu.org/packages/cl-sdl2/0.0.0-1.bb2aa2a/)) with all linkage to *.so libraries so preparing for dev is very
simple via `guix shell -D cl-virality`.

Thanks

**Comment by psilord** [comment]
ViralityEngine currently is an experimental game engine and will probably go through a lot of API changes for a good while yet. In fact it is still the case that the head of the master and develop branches might not even compile (or compile and work everywhere) while we work on it. Our recommendation at this time is please don't package ViralityEngine for this distribution because 1) it is very unstable and in flux, and 2) we don't know how the packaging of ViralityEngine in Guix affects developing a game with it.

**Comment by jgarte** [comment]
You can add a manifest for development purposes on Guix to build from the latest commit similar to this:

https://github.com/atlas-engineer/nyxt/blob/master/build-scripts/nyxt.scm
